name: actions
run-name: cmake
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cmake build
        run: cmake -H. -B_build
      - name: cmake --build
        run: cmake --build _build
